### ISSUE TITLE
Consultation

### ISSUE THREAD

**Issue by fermani10** [An0nimia/DeezloaderBIB_bot#40]
Hello. Previously I used this repository and I want to know if they are going to update it. It seems to me an incredible bot, thanks in advance.

**Comment by An0nimia** [comment]
@fermani10 I don't know, I will think about it, because last time I did it, a lot of people used it for their own purpose

**Comment by fermani10** [comment]
I would be very grateful .. thank you in advance

**Comment by adoboligh1** [comment]
> @fermani10 I don't know, I will think about it, because last time I did it, a lot of people used it for their own purpose

I guess it all came to you not receiving any donations or getting credit for your work, highly agree with you. but await an update we will thanks for your time!

**Comment by DeveloperLeon** [comment]
> @fermani10 I don't know, I will think about it, because last time I did it, a lot of people used it for their own purpose


So I would be very happy about an update if there is one, I find the bot you have made aboslut great
Thanks for your work. I would even be willing to make a small donation because the offer is just great

**Comment by An0nimia** [comment]
@DeveloperLeon One day, but I don't think too soon

**Comment by DeveloperLeon** [comment]
> One day, but I don't think too soon

no problem, no stress. Thank you

**Comment by DeveloperLeon** [comment]
> @DeveloperLeon One day, but I don't think too soon

Do you happen to know how to fix the problem with the Spotify link? every time I send a Spotify link it tells me that the link was not found, and I get an error in the log.

**Comment by An0nimia** [comment]
@DeveloperLeon Not really It worked time ago

**Comment by DeveloperLeon** [comment]
@An0nimia OK, thanks anyway, it works in your new bot, that's why I was wondering.

**Comment by An0nimia** [comment]
@DeveloperLeon You've already tried it by yourself, first?

**Comment by 9Mad-Max5** [comment]
> @An0nimia OK, thanks anyway, it works in your new bot, that's why I was wondering.

def generate_token():
	return oauth2.SpotifyClientCredentials(
		client_id = "c6b23f1e91f84b6a9361de16aba0ae17",
		client_secret = "237e355acaa24636abc79f1a089e6204"
	).get_access_token()
	
needs to be changed by this:
	).get_access_token(as_dict=False)

**Comment by DeveloperLeon** [comment]
> > @An0nimia OK, thanks anyway, it works in your new bot, that's why I was wondering.
> 
> def generate_token():
> return oauth2.SpotifyClientCredentials(
> client_id = "c6b23f1e91f84b6a9361de16aba0ae17",
> client_secret = "237e355acaa24636abc79f1a089e6204"
> ).get_access_token()
> 
> needs to be changed by this:
> ).get_access_token(as_dict=False)

Thanks a lot 😁

**Comment by An0nimia** [comment]
NEW VERSION AVAILABLE CLOSING THIS :)
