### ISSUE TITLE
i have a question

### ISSUE THREAD

**Issue by DeveloperLeon** [An0nimia/DeezloaderBIB_bot#41]
Hey, where can I enter my bot token and my ARL token?

**Comment by vincreator** [comment]
on
https://github.com/An0nimia/DeezloaderBIB_bot/blob/master/configs/set_configs.py

**Comment by An0nimia** [comment]
@vincreator yes you can

**Comment by DeveloperLeon** [comment]
> @vincreator yes you can

Thanks for your great work

**Comment by DeveloperLeon** [comment]
> on
> https://github.com/An0nimia/DeezloaderBIB_bot/blob/master/configs/set_configs.py

Thank you

**Comment by vincreator** [comment]
> @vincreator yes you can

excuse me sir
should create a deez settings.ini file? 😄

**Comment by An0nimia** [comment]
Close comment, please
